---
title: "Resume"
---

###EXPERIENCE
> #### [Dobson Dolphin Pool](https://www.facebook.com/dobsondolphins/), Dobson NC — Lifeguard
MAY 2013 - AUGUST 2016, MAY 2018 - AUGUST 2018  (Open seasonally)  
I worked for Dobson Dolphin Pool for five years and helped to maintain a family friendly environment while also protecting the patrons of the pool. My duties included cleaning and making sure the pool was presentable for patrons and any other jobs requested by pool maintenance. My last year working at Dobson I was assigned Head Lifeguard and Pool Manager. Those duties included those of a regular lifeguard along with other: making schedules, finding replacements for lifeguards who couldn’t come in, dealing with any issues or concerns from the patrons or lifeguards and completing tasks asked of me by the board.

> #### [Camp Raven Knob](https://www.ravenknob.com/), Lowgap NC — Instructor/Lifeguard
MAY 2017 - AUGUST 2017 (Open Seasonally)  
I worked at Camp Raven Knob as an Instructor and Lifeguard. Camp Raven Knob is a Boy Scout camp which takes pride in helping scouts to earn their patches and also give them an exciting and enjoyable experience while at Camp Raven Knob. My job was to ensure the safety of scouts while they attended camp and to teach them their appropriate material so that they may earn their required aquatic badges. My lessons included lifesaving, swimming, swimming(Beginner/Non-swimmer), and Kayaking.

> #### [Surry Community College](https://surry.edu/), Dobson NC — Tutor/Work Study
AUGUST 2017 - AUGUST 2018  
While I attended classes at Surry I was the a Tutor and Work Study. My responsibilities included helping students with assignments and understanding fully the material required of them. Most of the time students would use the tutoring room as a study room and when they had a question we would work through problems together until they understood the problem.
My work study responsibilities included inputting tutoring hours, making sure referral forms were signed and any other tasks asked of me. When working at the desk I would answer the phone and guide students in the proper steps to get tutoring for any subject.

###EDUCATION

> #### [Surry Community College](https://surry.edu/), Dobson NC — AS Degree
AUGUST 2016 - AUGUST 2018  
For the first two years of my college experience I attended Surry Community College. While here I took my GED courses and completed many math courses that would help me move toward my intended major in Mathematics. While I attended Surry I was their Precalculus and  Calculus Tutor and a Work Study for the Academic Support Center.

> #### [Appalachian State University](https://www.appstate.edu/), Boone NC — Mathematics BA (Currently Working Towards)
AUGUST 2018 - CURRENT  
I am currently attending Appalachian State University where I am trying to obtain a BA in Mathematics. I am currently involved in a co-ed a cappella group called Strong Ties and while education is important I could not be happier with the professors here at Appalachian State and the community as a whole.
